swagger: "2.0"
info:
  version: "1.0.0"
  title: E2E Treinamentos - Administrar Usuários
  description: API para gerenciamento de usuários

basePath: /api
schemes:
  - http
host: localhost:8080

paths:
  /users:
    post:
      tags:
        - User
      summary: Cadastrar um novo usuário
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          description: Objeto do usuário a ser cadastrado
          required: true
          schema:
            $ref: "#/definitions/User"
        - in: header
          name: Authorization
          type: string
          required: false
          description: Cabeçalho de autorização (Basic Authentication)
      responses:
        201:
          description: Usuário cadastrado com sucesso!
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: Erro ao cadastrar usuário, validar mensagem de acordo com a regra de negócio.
          schema:
            $ref: "#/definitions/ApiResponse"

    get:
      tags:
        - User
      summary: Obter a lista de usuários
      produces:
        - application/json
      responses:
        200:
          description: Lista de usuários obtida com sucesso!
          schema:
            type: array
            items:
              $ref: "#/definitions/User"

  /api/users/delete:
    delete:
      tags:
        - User
      summary: Deletar todos os usuários
      produces:
        - application/json
      responses:
        200:
          description: Todos os usuários foram deletados com sucesso!
          schema:
            $ref: "#/definitions/ApiResponse"
        404:
          description: Nenhum usuário encontrado para deletar.
          schema:
            $ref: "#/definitions/ApiResponse"

definitions:
  User:
    type: object
    properties:
      usuario:
        type: string
      senha:
        type: string
      nomeCompleto:
        type: string
  ApiResponse:
    type: object
    properties:
      message:
        type: string
